a = ("Tara aleasa de tine este:")
b = ("Orasul ales de  tine este:")
c = ("Numarul ales de tine este:")
print(a)
a1 = str(input())
print(b)
b1 = str(input())
print(c)
c1 = str(input())
print("Super! Si eu am vizitat", a1, ",iar in", b1, "am petrecut minunat", c1, "zile")
